name: puppeteer-chrome
description: Run Test through Puppeteer, the headless chrome Node API
author: tj-actions
inputs:
  token:
    description: '[GITHUB_TOKEN](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow) or a repo scoped [Personal Access Token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)'
    required: true
    default: ${{ github.token }}
  node-version:
    description: 'Node version'
    required: false
    default: '14'
  args:
    description: 'Command to run puppeteer'
    required: true
  image:
    description: 'Docker image to use'
    required: false
    default: 'ghcr.io/tj-actions/puppeteer:node-16'

runs:
  using: 'composite'
  steps:
    - name: Docker Run
      uses: tj-actions/docker-run-action@v1
      with:
        image: ${{ inputs.image }}
        args: ${{ inputs.args }}

branding:
  icon: camera-off
  color: white
