name: puppeteer
description: Run Test through Puppeteer, the headless chrome Node API
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  node-version:
    description: 'Node version'
    required: false
    default: '10'
  run-args:
    description: 'Run argument'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --build-arg NODE_VERSION=${{ inputs.node-version }} ${{ input.run-args }}
branding:
  icon: camera-off
  color: green
