name: puppeteer-chrome
description: Run Test through Puppeteer, the headless chrome Node API
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  node-version:
    description: 'Node version'
    required: false
    default: '14'
  args:
    description: 'Command to run puppeteer'
    required: true

runs:
  using: 'composite'
  steps:
    - id: build
      run: docker build --build-arg NODE_VERSION=${{ inputs.node-version }} -t puppetter:local-node${{ inputs.node-version }} .
      shell: bash
    - id: run
      run: docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace puppetter:local-node${{ inputs.node-version }} ${{ inputs.args }}
      shell: bash
branding:
  icon: camera-off
  color: white
