name: puppeteer-chrome
description: Run Test through Puppeteer, the headless chrome Node API
author: tj-actions
inputs:
  files:
    description: 'Files to run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run puppeteer
      uses: tj-actions/docker-run-action@v2
      with:
        image: ghcr.io/puppeteer/puppeteer:19.4.1
        options: '-i --init --cap-add=SYS_ADMIN -v ${{ github.workspace }}:${{ github.workspace }}'
        args: bash -c 'while read -r file; do echo $file && echo "mkdir -p $(dirname /home/pptruser/$file)" && echo "cp ${{ github.workspace }}/$file /home/pptruser/$file" && echo "node $file"; done <<< "${{ inputs.files }}"'


branding:
  icon: camera-off
  color: white
