name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Test action
        uses: ./
        working-directory: ./test
        with:
          files: test.js
