name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        node-version: [14, 15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Test action with node ${{ matrix.node-version }}
        uses: ./
        with:
          node-version: ${{ matrix.node-version }}
          args: node test/test.js
