name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test puppeteer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action with node 10
        uses: ./
        with:
          node-version: '11'
      - name: Test action with node 11
        uses: ./
        with:
          node-version: '11'
      - name: Test action with node 12
        uses: ./
        with:
          node-version: '12'
      - name: Test action with node 13
        uses: ./
        with:
          node-version: '13'

