name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        node-version: [14, 15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Docker Build
        uses: docker/build-push-action@v3
        id: docker-build
        with:
          context: .
          load: true
          push: false
          build-args: NODE_VERSION=${{ inputs.node-version }}
          tags: ${{ github.repository }}:local-node-${{ inputs.node-version }}
          cache-from: |
            ghcr.io/${{ github.repository }}:node-${{ inputs.node-version }}
            type=gha
          cache-to: |
            type=gha,mode=max

      - name: Test action with node ${{ matrix.node-version }}
        uses: ./
        with:
          image: ${{ github.repository }}:local-node-${{ inputs.node-version }}
          node-version: ${{ matrix.node-version }}
          args: node test/test.js
