name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test puppeteer
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Test action with node 10
        uses: ./
        with:
          args: npx test/test.js
      - name: Test action with node 12
        uses: ./
        with:
          node-version: '12'
          args: npx test/test.js
      - name: Test action with node 14
        uses: ./
        with:
          node-version: '14'
          args: npx test/test.js
      - name: Test action with node 15
        uses: ./
        with:
          node-version: '15'
          args: npx test/test.js

