name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Test action
        uses: ./
        id: puppeteer-test
        with:
          files: test/test.js

      - name: Copy test output
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.puppeteer-test.outputs.container-id }}
          source: /home/pptruser/test.pdf
          destination: test.pdf

      - name: Display contents of test.pdf
        run: cat test.pdf
